builds:
  - goos:
    - darwin
    - windows
    - linux
    - freebsd
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/jckuester/awsls/internal.version={{.Version}} -X github.com/jckuester/awsls/internal.commit={{.ShortCommit}} -X github.com/jckuester/awsls/internal.date={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
- github:
    owner: rothgar
    name: homebrew-tap
  homepage: "https://github.com/jckuester/awsls"
  description: "A list command for AWS resources"
  folder: Formula

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
