package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/apex/log"
	"github.com/apex/log/handlers/cli"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/private/util"
)

const codeLayout = `// Code is generated by terratools. DO NOT EDIT.

%s
package %s

%s
`

func main() {
	log.SetHandler(cli.Default)
	log.SetLevel(log.DebugLevel)

	resourceTypes := ResourceTypes()

	err := writeResourceTypes("gen", resourceTypes)
	if err != nil {
		log.Fatal(err.Error())
	}
	log.Infof("Generated map of Terraform AWS resource types: %d", len(resourceTypes))
}

func writeResourceTypes(outputPath string, terraformTypes []string) error {
	err := os.MkdirAll(outputPath, 0775)
	if err != nil {
		return fmt.Errorf("failed to create directory: %s", err)
	}

	err = writeGoFile(
		filepath.Join(outputPath, "resourceTypes.go"),
		codeLayout,
		"",
		"gen",
		ResourceTypesGoCode(terraformTypes),
	)
	if err != nil {
		return fmt.Errorf("failed to write map of resource types to file: %s", err)
	}

	return nil
}

// ResourceTypesGoCode generates the Go code for the list of Terraform resource types.
func ResourceTypesGoCode(terraformTypes []string) string {
	var buf bytes.Buffer
	err := resourceTypesTmpl.Execute(&buf, terraformTypes)
	if err != nil {
		panic(err)
	}

	return strings.TrimSpace(buf.String())

}

var resourceTypesTmpl = template.Must(template.New("resourceTypes").Parse(`
// ResourceTypes is a list of all resource types supported by the Terraform AWS Provider.
var ResourceTypes = []string{
{{range .}}"{{.}}",
{{end}}}
`))

func writeGoFile(file string, layout string, args ...interface{}) error {
	return ioutil.WriteFile(file, []byte(util.GoFmt(fmt.Sprintf(layout, args...))), 0664)
}

// ResourceTypes returns a list of all resource types supported by the Terraform AWS Provider.
func ResourceTypes() []string {
	node, err := parser.ParseFile(token.NewFileSet(),
		"/home/jan/git/github.com/yoyolabsio/terraform-provider-aws/aws/provider.go",
		nil, 0)
	if err != nil {
		log.Fatalf(err.Error())
	}

	var result []string

	ast.Inspect(node, func(n ast.Node) bool {
		// look for a map called "ResourcesMap" that contains all the resource types
		resourcesMap, ok := n.(*ast.KeyValueExpr)
		if !ok {
			return true
		}

		resourceMapName, ok := resourcesMap.Key.(*ast.Ident)
		if !ok {
			return false
		}

		if resourceMapName.Name != "ResourcesMap" {
			return false
		}

		ast.Inspect(resourcesMap, func(n ast.Node) bool {
			mapEntry, ok := n.(*ast.KeyValueExpr)
			if !ok {
				return true
			}

			resourceType, ok := mapEntry.Key.(*ast.BasicLit)
			if !ok {
				return true
			}

			result = append(result, strings.Trim(resourceType.Value, "\""))

			return true
		})

		return true
	})

	return result
}

// GetResourceTypeFileName returns the name of the file that implements the resource of the given resource type.
func GetResourceTypeFileName(resourceType string) *string {
	node, err := parser.ParseFile(token.NewFileSet(),
		"/home/jan/git/github.com/yoyolabsio/terraform-provider-aws/aws/provider.go",
		nil, 0)
	if err != nil {
		log.Fatalf(err.Error())
	}

	var result *string

	ast.Inspect(node, func(n ast.Node) bool {
		mapEntry, ok := n.(*ast.KeyValueExpr)
		if !ok {
			return true
		}

		key, ok := mapEntry.Key.(*ast.BasicLit)
		if !ok {
			return true
		}

		if resourceType != strings.Trim(key.Value, "\"") {
			return false
		}

		resource, ok := mapEntry.Value.(*ast.CallExpr)
		if !ok {
			return false
		}

		resourceFuncName, ok := resource.Fun.(*ast.Ident)
		if !ok {
			return false
		}

		files, err := ioutil.ReadDir("/home/jan/git/github.com/yoyolabsio/terraform-provider-aws/aws")
		if err != nil {
			log.Fatal(err.Error())
		}

		for _, f := range files {
			if strings.HasPrefix(f.Name(), "resource_aws") {
				node, err := parser.ParseFile(token.NewFileSet(),
					"/home/jan/git/github.com/yoyolabsio/terraform-provider-aws/aws/"+f.Name(),
					nil, 0)
				if err != nil {
					log.Fatal(err.Error())
				}

				ast.Inspect(node, func(n ast.Node) bool {
					fn, ok := n.(*ast.FuncDecl)
					if !ok {
						return true
					}

					if fn.Name.Name == resourceFuncName.Name {
						result = aws.String(f.Name())
						return false
					}

					return true
				})
			}
		}
		return true
	})
	return result
}
